openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- description: Generated server url
  url: http://ec2-35-75-6-81.ap-northeast-1.compute.amazonaws.com:8080
paths:
  /entry/:
    get:
      operationId: getApi
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EntryResponseTestDto'
          description: OK
      tags:
      - api-controller
      x-accepts: '*/*'
    post:
      operationId: postApi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntryRequestDto'
        required: true
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EntryResponseDto'
          description: OK
      tags:
      - api-controller
      x-content-type: application/json
      x-accepts: '*/*'
  /entry/test:
    get:
      operationId: getTestApi
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/EntryResponseTestDto'
          description: OK
      tags:
      - api-controller
      x-accepts: '*/*'
components:
  schemas:
    AddressDto:
      example:
        prefectures: prefectures
        municipalities: municipalities
      properties:
        prefectures:
          type: string
        municipalities:
          type: string
      required:
      - municipalities
      - prefectures
      type: object
    CustomerDto:
      example:
        address:
          prefectures: prefectures
          municipalities: municipalities
        name: name
      properties:
        name:
          type: string
        address:
          $ref: '#/components/schemas/AddressDto'
      required:
      - name
      type: object
    EntryRequestDto:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        id: id
        customer:
          address:
            prefectures: prefectures
            municipalities: municipalities
          name: name
      properties:
        id:
          type: string
        customer:
          $ref: '#/components/schemas/CustomerDto'
        date:
          format: date-time
          type: string
      required:
      - customer
      - id
      type: object
    EntryResponseDto:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        result: result
        name: name
        id: id
      properties:
        id:
          type: string
        name:
          type: string
        date:
          format: date-time
          type: string
        result:
          type: string
      required:
      - result
      type: object
    EntryResponseTestDto:
      example:
        text: text
      properties:
        text:
          type: string
      required:
      - text
      type: object

